### ISSUE TITLE
hardware support question

### ISSUE THREAD

**Issue by jinz2014** [intel/intel-extension-for-openxla#12]
Does it make sense to support more Intel GPU devices (e.g. Gen9, ARC) ?

Hardware Requirements
Verified Hardware Platforms:

Intel® Data Center GPU Max Series

Intel® Data Center GPU Flex Series 170

**Comment by juehang** [comment]
I would appreciate this too; it is quite hard to recommend Intel hardware for work use if I can't try the workflow on my own at home, and Intel also has a really cheap 16GB card which would be great for scientific computing and machine learning.

**Comment by fredlarochelle** [comment]
Just my 2 cents, I would choose an approach similar to Nvidia any day of the week over an approach similar to AMD...

**Comment by fredlarochelle** [comment]
I also haven't look into it since the days that Arc "support" was through ITEX, but right now, is Arc unofficially supported?

**Comment by juehang** [comment]
> Just my 2 cents, I would choose an approach similar to Nvidia any day of the week over an approach similar to AMD...

Agreed; as someone who's a HPC user I can't really imagine suggesting Intel hardware because I can't just try the workflow at home, and I can't justify spending my own money if support is spotty.

**Comment by Zantares** [comment]
Arc is on the way. Since this Extension is still in an experimental phase and JAX API is not stable, we can't commit full support of this Extension on all intel platforms.

**Comment by Zantares** [comment]
Please feel free to discuss if you have any other questions.

**Comment by Zantares** [comment]
This question has been inactive for more than 2 weeks, will close it soon if no more feedback, thanks!
