### ISSUE TITLE
When is the PyTorch supported? 

### ISSUE THREAD

**Issue by wwtghx** [intel/intel-extension-for-openxla#23]
As title.

**Comment by akarshanbiswas** [comment]
This should be closed. The repo for PyTorch is [here](https://github.com/intel/intel-extension-for-pytorch)

**Comment by Zantares** [comment]
Pytorch support is not related to this repo. Please edit the title or submit a new issue if you are talking about TorchXLA, thanks!

**Comment by Zantares** [comment]
This question has been inactive for more than 2 weeks, will close it soon if no more feedback, thanks!
