### ISSUE TITLE
There is a version mismatch error with the latest jax.

### ISSUE THREAD

**Issue by akarshanbiswas** [intel/intel-extension-for-openxla#27]
I have seen it has been updated in readme but it throws an error:

```
RuntimeError: Unable to initialize backend 'xpu': INVALID_ARGUMENT: Mismatched PJRT plugin PJRT API version (0.38) and framework PJRT API version 0.40). (you may need to uninstall the failing plugin package, or set JAX_PLATFORMS=cpu to skip this backend.)
```

Will it be updated in pypi or do I have to build it from source?

**Comment by ShengYang1** [comment]
We are working on the latest pypi wheel and it will be released soon. If you want to try the latest feature now, you'd better build it from source.

**Comment by akarshanbiswas** [comment]
@ShengYang1 Thank you. I actually downgraded JAX for now..

**Comment by akarshanbiswas** [comment]
Closing this as new version is released! Thank you!
